Fix weird curl certificate revocation error:
tdma_api.clib.CLibException: TDMA_API_CONNECT_ERROR: curl connection error (35): schannel: next InitializeSecurityContext failed: Unknown error (0x80092013) - The revocation function was unable to check revocation because the revocation server was offline.(curl code=35)